spring:
  application:
    name: carfix-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/carfix
    username: backend
    password: carfix

  jpa:
    properties:
      hibernate.default_schema: carfix

  flyway:
    locations: classpath:db/migration
    schemas: carfix
    default-schema: carfix
    table: flyway_schema_history
    baseline-version: 0

  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: staging
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

---

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET,OPTIONS"
        allowed-headers: "*"
        max-age: 3600
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true #does not work for some reason
    java:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true #does not work