SET search_path TO carfix;

CREATE TABLE files (
                       file_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       storage_bucket varchar(63)  NOT NULL,
                       storage_key varchar(512)  NOT NULL,
                       content_type varchar(50)  NOT NULL,
                       bytes bigint  NOT NULL,
                       width int  NOT NULL,
                       height int  NOT NULL,
                       sha256_hex varchar(64)  NOT NULL,
                       alt_text varchar(255)  NOT NULL,
                       variants jsonb  NOT NULL,
                       status text  NOT NULL,
                       created_at timestamptz  NOT NULL DEFAULT now(),
                       deleted_at timestamptz,

                       CONSTRAINT check_files_status
                           CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED', 'DELETED', 'ARCHIVED'))
);

