SET search_path TO carfix;

CREATE TABLE car_brands (
                            car_brand_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name varchar(100)  NOT NULL UNIQUE
);

