SET search_path TO carfix;

CREATE TABLE car_models (
                            car_model_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name varchar(50)  NOT NULL,
                            car_brand_id int  NOT NULL
);

