SET search_path TO carfix;

CREATE TABLE model_versions (
                                 model_version_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                 name varchar(50)  NOT NULL,
                                 start_production smallint  NOT NULL,
                                 end_production smallint,
                                 car_model_id int  NOT NULL
);
