SET search_path TO carfix;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE addresses (
                           address_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           building_number varchar(10)  NOT NULL,
                           flat_number varchar(10)  NULL,
                           street_id bigint  NOT NULL,
                           postal_code_id int  NOT NULL
);

CREATE TABLE streets (
                         street_id bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100)  NOT NULL,
                         city_id int  NOT NULL
);

CREATE TABLE cities (
                        city_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100)  NOT NULL,
                        region_id int  NOT NULL
);

CREATE TABLE regions (
                         region_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100)  NOT NULL,
                         countries_iso char(2)  NOT NULL
);

CREATE TABLE countries (
                           iso char(2)  PRIMARY KEY,
                           name varchar(100)  NOT NULL,
--TODO temporary solution
                       CONSTRAINT check_countries_iso
                            CHECK (iso IN (
                                           'US', 'CA', 'GB', 'DE', 'FR', 'IT', 'ES', 'PL', 'UA', 'PT',
                                           'NL', 'SE', 'NO', 'FI', 'DK', 'CH', 'AT', 'BE', 'CZ', 'SK',
                                           'HU', 'RO', 'BG', 'GR', 'TR', 'IE', 'IS', 'AU', 'NZ', 'JP',
                                           'CN', 'KR', 'IN', 'BR', 'AR', 'MX', 'ZA', 'EG', 'IL', 'SA', 'AE'
                                ))
);

CREATE TABLE postal_codes (
                              postal_code_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              code varchar(10) NOT NULL,
                              city_id int  NOT NULL
);

CREATE UNIQUE INDEX ui_postal_codes_city_code
    ON postal_codes (city_id, code);

CREATE TABLE users (
                       user_id uuid  DEFAULT gen_random_uuid() PRIMARY KEY,
                       name varchar(50)  NOT NULL,
                       surname varchar(50)  NOT NULL,
                       phone_number varchar(15)  NOT NULL,
                       ph_country_code varchar(4)  NOT NULL,
                       email varchar(30)  NOT NULL,
                       password text  NOT NULL,
                       date_of_birth date  NULL,
                       address_id int  NULL,
--TODO Temporary solution
                       CONSTRAINT check_uses_ph_country_code
                            CHECK (ph_country_code IN (
                           '+1',
                            '+7',
                            '+20',
                            '+27',
                            '+30',
                            '+31',
                            '+32',
                            '+33',
                            '+34',
                            '+36',
                            '+39',
                            '+40',
                            '+41',
                            '+43',
                            '+44',
                            '+45',
                            '+46',
                            '+47',
                            '+48',
                            '+49',
                            '+51',
                            '+52',
                            '+53',
                            '+54',
                            '+55',
                            '+56',
                            '+57',
                            '+58',
                            '+60',
                            '+61',
                            '+62',
                            '+63',
                            '+64',
                            '+65',
                            '+66',
                            '+81',
                            '+82',
                            '+84',
                            '+86',
                            '+90',
                            '+91',
                            '+92',
                            '+93',
                            '+94',
                            '+95',
                            '+98',
                            '+211',
                            '+212',
                            '+213',
                            '+216',
                            '+218',
                            '+220',
                            '+221',
                            '+222',
                            '+223',
                            '+224',
                            '+225',
                            '+226',
                            '+227',
                            '+228',
                            '+229',
                            '+230',
                            '+231',
                            '+232',
                            '+233',
                            '+234',
                            '+235',
                            '+236',
                            '+237',
                            '+238',
                            '+239',
                            '+240',
                            '+241',
                            '+242',
                            '+243',
                            '+244',
                            '+245',
                            '+246',
                            '+248',
                            '+249',
                            '+250',
                            '+251',
                            '+252',
                            '+253',
                            '+254',
                            '+255',
                            '+256',
                            '+257',
                            '+258',
                            '+260',
                            '+261',
                            '+262',
                            '+263',
                            '+264',
                            '+265',
                            '+266',
                            '+267',
                            '+268',
                            '+269',
                            '+290',
                            '+291',
                            '+297',
                            '+298',
                            '+299',
                            '+350',
                            '+351',
                            '+352',
                            '+353',
                            '+354',
                            '+355',
                            '+356',
                            '+357',
                            '+358',
                            '+359',
                            '+370',
                            '+371',
                            '+372',
                            '+373',
                            '+374',
                            '+375',
                            '+376',
                            '+377',
                            '+378',
                            '+379',
                            '+380',
                            '+381',
                            '+382',
                            '+383',
                            '+385',
                            '+386',
                            '+387',
                            '+389',
                            '+420',
                            '+421',
                            '+423',
                            '+500',
                            '+501',
                            '+502',
                            '+503',
                            '+504',
                            '+505',
                            '+506',
                            '+507',
                            '+508',
                            '+509',
                            '+590',
                            '+591',
                            '+592',
                            '+593',
                            '+594',
                            '+595',
                            '+596',
                            '+597',
                            '+598',
                            '+599',
                            '+670',
                            '+672',
                            '+673',
                            '+674',
                            '+675',
                            '+676',
                            '+677',
                            '+678',
                            '+679',
                            '+680',
                            '+681',
                            '+682',
                            '+683',
                            '+685',
                            '+686',
                            '+687',
                            '+688',
                            '+689',
                            '+690',
                            '+691',
                            '+692',
                            '+850',
                            '+852',
                            '+853',
                            '+855',
                            '+856',
                            '+870',
                            '+871',
                            '+872',
                            '+873',
                            '+874',
                            '+875',
                            '+876',
                            '+877',
                            '+878',
                            '+879',
                            '+880',
                            '+881',
                            '+882',
                            '+883',
                            '+886',
                            '+888',
                            '+960',
                            '+961',
                            '+962',
                            '+963',
                            '+964',
                            '+965',
                            '+966',
                            '+967',
                            '+968',
                            '+970',
                            '+971',
                            '+972',
                            '+973',
                            '+974',
                            '+975',
                            '+976',
                            '+977',
                            '+992',
                            '+993',
                            '+994',
                            '+995',
                            '+996',
                            '+998'
                            ))
);

-- check_customers_status option list can be changed
CREATE TABLE customers (user_id uuid  PRIMARY KEY,
                        status text  NOT NULL

                            CONSTRAINT check_customers_status
                                CHECK (status IN ('active', 'suspended'))
);

CREATE TABLE owners (
                        user_id uuid  PRIMARY KEY,
                        business_name varchar(100)  NOT NULL,
                        vat_in varchar(15)  NOT NULL,
                        regon varchar(9)  NOT NULL
);

CREATE TABLE employees (
                           user_id uuid  PRIMARY KEY,
                           status text  NOT NULL,
                           notes text,
                           salary decimal(10,2)  NOT NULL,
                           branch_id uuid  NOT NULL,

                           CONSTRAINT check_employees_status
                               CHECK (status IN ('busy', 'active', 'free', 'suspended'))
);

CREATE TABLE car_profiles (
                              car_profile_id uuid  DEFAULT gen_random_uuid() PRIMARY KEY,
                              name varchar(100)  NOT NULL,
                              vin char(17),
                              plates varchar(10),
                              service_certificate_date date,
                              insurance_date date,
                              customer_id uuid  NOT NULL,
                              file_id int,
                              model_generation_id int  NOT NULL
);

CREATE TABLE model_generations (
                                   model_generation_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                   name varchar(50)  NOT NULL,
                                   start_production smallint  NOT NULL,
                                   end_production smallint,
                                   car_model_id int  NOT NULL
);


CREATE TABLE car_models (
                            car_model_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name varchar(50)  NOT NULL,
                            car_brand_id int  NOT NULL
);

CREATE TABLE car_brands (
                            car_brand_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name varchar(100)  NOT NULL UNIQUE
);

CREATE TABLE bookings (
                          booking_id uuid  DEFAULT gen_random_uuid() PRIMARY KEY,
                          date date  NOT NULL,
                          status text  NOT NULL,
                          start_time timetz  NOT NULL,
                          end_time timetz  NOT NULL,
                          branch_id uuid  NOT NULL,
                          car_profile_id uuid  NOT NULL

                              CONSTRAINT check_bookings_status
                                  CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled'))
);

CREATE TABLE reviews (
                         review_id uuid  DEFAULT gen_random_uuid() PRIMARY KEY,
                         stars_number int  NOT NULL,
                         contents text,
                         booking_id uuid  NOT NULL
);

CREATE TABLE car_brands_branches (
                                     car_brand_id int,
                                     branch_id uuid,

                                     CONSTRAINT pk_car_brands_branches PRIMARY KEY (car_brand_id, branch_id)
);

CREATE TABLE branches_files (
                                file_id int,
                                branch_id uuid,
                                is_public boolean  NOT NULL DEFAULT TRUE,
                                display_order int  NOT NULL,

                                CONSTRAINT pk_branches_files PRIMARY KEY (file_id, branch_id)
);

CREATE TABLE bookings_equipment (
                                    booking_id uuid,
                                    equipment_id int,

                                    CONSTRAINT bookings_equipment_pk PRIMARY KEY (equipment_id,booking_id)
);

CREATE TABLE branches (
                          branch_id uuid  DEFAULT gen_random_uuid() PRIMARY KEY,
                          name varchar(100)  NOT NULL,
                          phone_number varchar(17)  NOT NULL,
                          email varchar(50)  NOT NULL,
                          status text  NOT NULL,
                          tz text  NOT NULL,
                          address_id int  NOT NULL,
                          owner_id uuid  NOT NULL,

                          CONSTRAINT check_branches_status
                              CHECK (status IN ('verification_pending', 'active', 'suspended'))
);

CREATE TABLE files (
                       file_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       storage_bucket varchar(63)  NOT NULL,
                       storage_key varchar(512)  NOT NULL,
                       content_type varchar(50)  NOT NULL,
                       bytes bigint  NOT NULL,
                       width int  NOT NULL,
                       height int  NOT NULL,
                       sha256_hex varchar(64)  NOT NULL,
                       alt_text varchar(255)  NOT NULL,
                       variants jsonb  NOT NULL,
                       status text  NOT NULL,
                       created_at timestamptz  NOT NULL DEFAULT now(),
                       deleted_at timestamptz,

                       CONSTRAINT check_files_status
                           CHECK (status IN ('pending', 'processed', 'failed', 'deleted', 'archived'))
);

CREATE TABLE opening_hours (
                               opening_hour_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               day_of_week text  NOT NULL,
                               start_time time  NOT NULL,
                               close_time time  NOT NULL,
                               branch_id uuid  NOT NULL,

                               CONSTRAINT check_opening_hours
                                   CHECK (day_of_week
                                       IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')
                                       )
);

CREATE TABLE opening_hours_exceptions (
                                          exceptions_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          date date  NOT NULL,
                                          start_time time,
                                          close_time time,
                                          is_open boolean  NOT NULL,
                                          reason varchar(300),
                                          branch_id uuid  NOT NULL
);

CREATE TABLE equipment (
                           equipment_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name varchar(100)  NOT NULL,
                           notes text,
                           status text NOT NULL,
                           equipment_type_id int  NOT NULL,
                           branch_id uuid  NOT NULL,

                           CONSTRAINT check_equipment_status
                               CHECK (status IN ('active', 'suspended'))
);

CREATE TABLE equipment_availability (
                                        equipment_availability_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        available_time tsrange  NOT NULL,
                                        date date  NOT NULL,
                                        equipment_id int  NOT NULL,

                                        CONSTRAINT gist_available_time_exclusion_equipment_availability
                                            EXCLUDE USING gist (
            date WITH =,
            available_time WITH &&,
            equipment_id WITH =
        ),

                                        CONSTRAINT check_available_time_valid_range_equipment_availability
                                            CHECK (lower(available_time) < upper(available_time)),
                                        CONSTRAINT check_available_time_not_empty_range_equipment_availability
                                            CHECK (NOT isempty(available_time)),
                                        CONSTRAINT check_available_time_has_bounds_equipment_availability
                                            CHECK (NOT lower_inf(available_time) AND NOT upper_inf(available_time)),

                                        CONSTRAINT check_available_time_within_one_date_equipment_availability
                                            CHECK (
                                                lower(available_time) >= date::timestamp
                                                    AND
                                                upper(available_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );


CREATE TABLE equipment_bookings (
                                    equipment_booking_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    booked_time tsrange  NOT NULL,
                                    date date  NOT NULL,
                                    equipment_id int  NOT NULL,

                                    CONSTRAINT gist_booked_time_exclusion_equipment_bookings
                                        EXCLUDE USING gist (
            date WITH =,
            booked_time WITH &&,
            equipment_id WITH =
        ),

                                    CONSTRAINT check_booked_time_valid_range_equipment_bookings
                                        CHECK (lower(booked_time) < upper(booked_time)),
                                    CONSTRAINT check_booked_time_not_empty_range_equipment_bookings
                                        CHECK (NOT isempty(booked_time)),
                                    CONSTRAINT check_booked_time_has_bounds_equipment_bookings
                                        CHECK (NOT lower_inf(booked_time) AND NOT upper_inf(booked_time)),

                                    CONSTRAINT check_available_time_within_one_date_equipment_bookings
                                        CHECK (
                                            lower(booked_time) >= date::timestamp
                                                AND
                                            upper(booked_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );



CREATE TABLE equipment_types (
                                 equipment_type_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name varchar(40)  NOT NULL
);

CREATE TABLE service_bays (
                              service_bay_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name varchar(100)  NOT NULL,
                              status text NOT NULL ,
                              notes text,
                              service_bay_type_id int  NOT NULL,
                              branch_id uuid  NOT NULL,

                              CONSTRAINT check_service_bays_status
                                  CHECK (status IN ('active', 'suspended'))
);

CREATE TABLE service_bay_types (
                                   service_bay_type_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name varchar(40)  NOT NULL
);

CREATE TABLE service_bays_availability (
                                           service_bays_availability_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           available_time tsrange  NOT NULL,
                                           date date  NOT NULL,
                                           service_bay_id int  NOT NULL,

                                           CONSTRAINT gist_available_time_exclusion_service_bays_availability
                                               EXCLUDE USING gist (
            date WITH =,
            available_time WITH &&,
            service_bay_id WITH =
        ),

                                           CONSTRAINT check_available_time_valid_range_service_bays_availability
                                               CHECK (lower(available_time) < upper(available_time)),
                                           CONSTRAINT check_available_time_not_empty_range_service_bays_availability
                                               CHECK (NOT isempty(available_time)),
                                           CONSTRAINT check_available_time_has_bounds_service_bays_availability
                                               CHECK (NOT lower_inf(available_time) AND NOT upper_inf(available_time)),

                                           CONSTRAINT check_available_time_within_one_date_service_bays_availability
                                               CHECK (
                                                   lower(available_time) >= date::timestamp
                                                       AND
                                                   upper(available_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

CREATE TABLE service_bays_bookings (
                                       service_bays_booking_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       booked_time tsrange  NOT NULL,
                                       date date  NOT NULL,
                                       service_bay_id int  NOT NULL,

                                       CONSTRAINT gist_booked_time_exclusion_service_bays_bookings
                                           EXCLUDE USING gist (
            date WITH =,
            booked_time WITH &&,
            service_bay_id WITH =
        ),

                                       CONSTRAINT check_booked_time_valid_range_service_bays_bookings
                                           CHECK (lower(booked_time) < upper(booked_time)),
                                       CONSTRAINT check_booked_time_not_empty_range_service_bays_bookings
                                           CHECK (NOT isempty(booked_time)),
                                       CONSTRAINT check_booked_time_has_bounds_service_bays_bookings
                                           CHECK (NOT lower_inf(booked_time) AND NOT upper_inf(booked_time)),

                                       CONSTRAINT check_available_time_within_one_date_service_bays_bookings
                                           CHECK (
                                               lower(booked_time) >= date::timestamp
                                                   AND
                                               upper(booked_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

CREATE TABLE services (
                          service_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(100)  NOT NULL,
                          description varchar(500),
                          duration_minutes smallint  NOT NULL,
                          price decimal(7,2)  NOT NULL,
                          status text  NOT NULL,
                          service_bay_id int  NOT NULL,
                          service_category_id int  NOT NULL,

                          CONSTRAINT check_services_status
                              CHECK (status IN ('active', 'suspended'))
);

CREATE TABLE services_equipment (
                                    equipment_id int,
                                    service_id int,

                                    CONSTRAINT services_equipment_pk PRIMARY KEY (service_id,equipment_id)
);

CREATE TABLE service_categories (
                                    service_category_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar(50)  NOT NULL
);

CREATE TABLE bookings_services (
                                   booking_id uuid,
                                   service_id int,

                                   CONSTRAINT bookings_services_pk PRIMARY KEY (booking_id,service_id)
);

CREATE TABLE roles (
                       role_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(50)  NOT NULL
);

CREATE TABLE roles_services (
                                service_id int,
                                role_id int,

                                CONSTRAINT roles_services_pk PRIMARY KEY (service_id,role_id)
);

CREATE TABLE employees_roles (
                                 user_id uuid,
                                 role_id int,

                                 CONSTRAINT pk_employees_roles PRIMARY KEY (user_id, role_id)
);

CREATE TABLE employees_availability (
                                        employee_availability_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                        available_time tsrange  NOT NULL,
                                        date date  NOT NULL,
                                        employee_id uuid  NOT NULL,

                                        CONSTRAINT gist_available_time_exclusion_employees_availability
                                            EXCLUDE USING gist (
            date WITH =,
            available_time WITH &&,
            employee_id WITH =
        ),

                                        CONSTRAINT check_available_time_valid_range_employees_availability
                                            CHECK (lower(available_time) < upper(available_time)),
                                        CONSTRAINT check_available_time_not_empty_range_employees_availability
                                            CHECK (NOT isempty(available_time)),
                                        CONSTRAINT check_available_time_has_bounds_employees_availability
                                            CHECK (NOT lower_inf(available_time) AND NOT upper_inf(available_time)),

                                        CONSTRAINT check_available_time_within_one_date_employees_availability
                                            CHECK (
                                                lower(available_time) >= date::timestamp
                                                    AND
                                                upper(available_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

CREATE TABLE employees_bookings (
                                    employee_booking_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    booked_time tsrange  NOT NULL,
                                    date date  NOT NULL,
                                    employee_id uuid  NOT NULL,

                                    CONSTRAINT gist_time_exclusion_employees_bookings
                                        EXCLUDE USING gist (
            date WITH =,
            booked_time WITH &&,
            employee_id WITH =
        ),

                                    CONSTRAINT check_available_time_valid_range_employees_bookings
                                        CHECK (lower(booked_time) < upper(booked_time)),
                                    CONSTRAINT check_available_time_not_empty_range_employees_bookings
                                        CHECK (NOT isempty(booked_time)),
                                    CONSTRAINT check_available_time_has_bounds_employees_bookings
                                        CHECK (NOT lower_inf(booked_time) AND NOT upper_inf(booked_time)),

                                    CONSTRAINT check_booked_time_within_one_date_employees_bookings
                                        CHECK (
                                            lower(booked_time) >= date::timestamp
                                                AND
                                            upper(booked_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

CREATE TABLE bookings_employees(
                                   booking_id uuid NOT NULL,
                                   employee_id uuid NOT NULL,

                                   CONSTRAINT pk_bookings_employees
                                       PRIMARY KEY (booking_id, employee_id)
);

ALTER TABLE addresses ADD CONSTRAINT fk_addresses_streets FOREIGN KEY (street_id) REFERENCES streets (street_id);
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_postal_codes FOREIGN KEY (postal_code_id) REFERENCES postal_codes (postal_code_id);
ALTER TABLE streets ADD CONSTRAINT fk_streets_cities FOREIGN KEY (city_id) REFERENCES cities (city_id);
ALTER TABLE cities ADD CONSTRAINT fk_cities_regions FOREIGN KEY (region_id) REFERENCES regions (region_id);
ALTER TABLE regions ADD CONSTRAINT fk_regions_countries FOREIGN KEY (countries_iso) REFERENCES countries (iso);
ALTER TABLE postal_codes ADD CONSTRAINT fk_postal_codes_cities FOREIGN KEY (city_id) REFERENCES cities (city_id);
ALTER TABLE users ADD CONSTRAINT fk_users_address FOREIGN KEY (address_id) REFERENCES addresses (address_id);
ALTER TABLE customers ADD CONSTRAINT fk_customers_users FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE owners ADD CONSTRAINT fk_owners_users FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE employees ADD CONSTRAINT fk_employees_users FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE employees ADD CONSTRAINT fk_employees_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE car_profiles ADD CONSTRAINT fk_car_profiles_customers FOREIGN KEY (customer_id) REFERENCES customers (user_id);
ALTER TABLE car_profiles ADD CONSTRAINT fk_car_profiles_files FOREIGN KEY (file_id) REFERENCES files (file_id);
ALTER TABLE car_profiles ADD CONSTRAINT fk_car_profiles_model_generations FOREIGN KEY (model_generation_id) REFERENCES model_generations (model_generation_id);
ALTER TABLE model_generations ADD CONSTRAINT fl_model_generations_car_models FOREIGN KEY (car_model_id) REFERENCES model_generations (model_generation_id);
ALTER TABLE car_models ADD CONSTRAINT fk_car_models_car_brands FOREIGN KEY (car_brand_id) REFERENCES car_brands (car_brand_id);
ALTER TABLE bookings ADD CONSTRAINT fk_bookings_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE bookings ADD CONSTRAINT fk_bookings_car_profiles FOREIGN KEY (car_profile_id) REFERENCES car_profiles (car_profile_id);
ALTER TABLE reviews ADD CONSTRAINT fk_reviews_bookings FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);
ALTER TABLE car_brands_branches ADD CONSTRAINT fk_car_brands_branches_car_brands FOREIGN KEY (car_brand_id) REFERENCES car_brands (car_brand_id);
ALTER TABLE car_brands_branches ADD CONSTRAINT fk_car_brands_branches_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE branches_files ADD CONSTRAINT fk_branches_files_files FOREIGN KEY (file_id) REFERENCES files (file_id);
ALTER TABLE branches_files ADD CONSTRAINT fk_branches_files_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE bookings_equipment ADD CONSTRAINT fk_bookings_equipment_bookings FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);
ALTER TABLE bookings_equipment ADD CONSTRAINT fk_bookings_equipment_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id);
ALTER TABLE branches ADD CONSTRAINT fk_branches_addresses FOREIGN KEY (address_id) REFERENCES addresses (address_id);
ALTER TABLE branches ADD CONSTRAINT fk_branches_owners FOREIGN KEY (owner_id) REFERENCES owners (user_id);
ALTER TABLE opening_hours ADD CONSTRAINT fk_opening_hours_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE opening_hours_exceptions ADD CONSTRAINT fk_opening_hours_exceptions_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE equipment ADD CONSTRAINT fk_equipment_equipment_types FOREIGN KEY (equipment_type_id) REFERENCES equipment_types (equipment_type_id);
ALTER TABLE equipment ADD CONSTRAINT fk_equipment_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE equipment_availability ADD CONSTRAINT fk_equipment_availability_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id);
ALTER TABLE equipment_bookings ADD CONSTRAINT fk_equipment_bookings_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id);
ALTER TABLE service_bays ADD CONSTRAINT fk_service_bays_service_bay_types FOREIGN KEY (service_bay_type_id) REFERENCES service_bay_types (service_bay_type_id);
ALTER TABLE service_bays ADD CONSTRAINT fk_service_bays_branches FOREIGN KEY (branch_id) REFERENCES branches (branch_id);
ALTER TABLE service_bays_availability ADD CONSTRAINT fk_service_bays_availability_service_bays FOREIGN KEY (service_bay_id) REFERENCES service_bays (service_bay_id);
ALTER TABLE service_bays_bookings ADD CONSTRAINT fk_service_bays_bookings_service_bays FOREIGN KEY (service_bay_id) REFERENCES service_bays (service_bay_id);
ALTER TABLE services ADD CONSTRAINT fk_services_service_bays FOREIGN KEY (service_bay_id) REFERENCES service_bays (service_bay_id);
ALTER TABLE services ADD CONSTRAINT fk_services_service_categories FOREIGN KEY (service_category_id) REFERENCES service_categories (service_category_id);
ALTER TABLE services_equipment ADD CONSTRAINT fk_services_recourses_recourses FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id);
ALTER TABLE services_equipment ADD CONSTRAINT fk_services_equipment_services FOREIGN KEY (service_id) REFERENCES services (service_id);
ALTER TABLE bookings_services ADD CONSTRAINT fk_bookings_services_bookings FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);
ALTER TABLE bookings_services ADD CONSTRAINT fk_bookings_services_services FOREIGN KEY (service_id) REFERENCES services (service_id);
ALTER TABLE roles_services ADD CONSTRAINT fk_roles_services_services FOREIGN KEY (service_id) REFERENCES services (service_id);
ALTER TABLE roles_services ADD CONSTRAINT fk_roles_services_roles FOREIGN KEY (role_id) REFERENCES roles (role_id);
ALTER TABLE employees_roles ADD CONSTRAINT fk_employees_roles_employees FOREIGN KEY (user_id) REFERENCES employees (user_id);
ALTER TABLE employees_roles ADD CONSTRAINT fk_employees_roles_roles FOREIGN KEY (role_id) REFERENCES roles (role_id);
ALTER TABLE employees_availability ADD CONSTRAINT fk_employees_availability_employees FOREIGN KEY (employee_id) REFERENCES employees (user_id);
ALTER TABLE employees_bookings ADD CONSTRAINT fk_employees_bookings_employees FOREIGN KEY (employee_id) REFERENCES employees (user_id);
ALTER TABLE bookings_employees ADD CONSTRAINT fk_bookings_employees_bookings FOREIGN KEY (booking_id) REFERENCES bookings (booking_id);
ALTER TABLE bookings_employees ADD CONSTRAINT fk_bookings_employees_employees FOREIGN KEY (employee_id) REFERENCES employees (user_id);
ALTER TABLE users ADD CONSTRAINT uq_users_address UNIQUE (address_id);
