SET search_path TO carfix;

CREATE TABLE equipment_types (
                                 equipment_type_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name varchar(40)  NOT NULL
);

