SET search_path TO carfix;

CREATE TABLE equipment (
                           equipment_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name varchar(100)  NOT NULL,
                           notes text,
                           status text NOT NULL,
                           equipment_type_id int  NOT NULL,
                           branch_id uuid  NOT NULL,

                           CONSTRAINT check_equipment_status
                               CHECK (status IN ('active', 'suspended'))
);

