SET search_path TO carfix;

CREATE TABLE equipment_bookings (
                                    equipment_booking_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    booked_time tsrange  NOT NULL,
                                    date date  NOT NULL,
                                    equipment_id int  NOT NULL,

                                    CONSTRAINT gist_booked_time_exclusion_equipment_bookings
                                        EXCLUDE USING gist (
            date WITH =,
            booked_time WITH &&,
            equipment_id WITH =
        ),

                                    CONSTRAINT check_booked_time_valid_range_equipment_bookings
                                        CHECK (lower(booked_time) < upper(booked_time)),
                                    CONSTRAINT check_booked_time_not_empty_range_equipment_bookings
                                        CHECK (NOT isempty(booked_time)),
                                    CONSTRAINT check_booked_time_has_bounds_equipment_bookings
                                        CHECK (NOT lower_inf(booked_time) AND NOT upper_inf(booked_time)),

                                    CONSTRAINT check_available_time_within_one_date_equipment_bookings
                                        CHECK (
                                            lower(booked_time) >= date::timestamp
                                                AND
                                            upper(booked_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

