SET search_path TO carfix;

CREATE TABLE service_bay_types (
                                   service_bay_type_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name varchar(40)  NOT NULL
);

