SET search_path TO carfix;

CREATE TABLE service_bays (
                              service_bay_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name varchar(100)  NOT NULL,
                              status text NOT NULL ,
                              notes text,
                              service_bay_type_id int  NOT NULL,
                              branch_id uuid  NOT NULL,

                              CONSTRAINT check_service_bays_status
                                  CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

