SET search_path TO carfix;

CREATE TABLE service_bays_availability (
                                           service_bays_availability_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           available_time tsrange  NOT NULL,
                                           date date  NOT NULL,
                                           service_bay_id int  NOT NULL,

                                           CONSTRAINT gist_available_time_exclusion_service_bays_availability
                                               EXCLUDE USING gist (
            date WITH =,
            available_time WITH &&,
            service_bay_id WITH =
        ),

                                           CONSTRAINT check_available_time_valid_range_service_bays_availability
                                               CHECK (lower(available_time) < upper(available_time)),
                                           CONSTRAINT check_available_time_not_empty_range_service_bays_availability
                                               CHECK (NOT isempty(available_time)),
                                           CONSTRAINT check_available_time_has_bounds_service_bays_availability
                                               CHECK (NOT lower_inf(available_time) AND NOT upper_inf(available_time)),

                                           CONSTRAINT check_available_time_within_one_date_service_bays_availability
                                               CHECK (
                                                   lower(available_time) >= date::timestamp
                                                       AND
                                                   upper(available_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

