SET search_path TO carfix;

CREATE TABLE service_bays_bookings (
                                       service_bays_booking_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       booked_time tsrange  NOT NULL,
                                       date date  NOT NULL,
                                       service_bay_id int  NOT NULL,

                                       CONSTRAINT gist_booked_time_exclusion_service_bays_bookings
                                           EXCLUDE USING gist (
            date WITH =,
            booked_time WITH &&,
            service_bay_id WITH =
        ),

                                       CONSTRAINT check_booked_time_valid_range_service_bays_bookings
                                           CHECK (lower(booked_time) < upper(booked_time)),
                                       CONSTRAINT check_booked_time_not_empty_range_service_bays_bookings
                                           CHECK (NOT isempty(booked_time)),
                                       CONSTRAINT check_booked_time_has_bounds_service_bays_bookings
                                           CHECK (NOT lower_inf(booked_time) AND NOT upper_inf(booked_time)),

                                       CONSTRAINT check_available_time_within_one_date_service_bays_bookings
                                           CHECK (
                                               lower(booked_time) >= date::timestamp
                                                   AND
                                               upper(booked_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

