SET search_path TO carfix;

CREATE TABLE service_categories (
                                    service_category_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar(50)  NOT NULL
);

