SET search_path TO carfix;

CREATE TABLE services (
                          service_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(100)  NOT NULL,
                          description varchar(500),
                          duration_minutes smallint  NOT NULL,
                          price decimal(7,2)  NOT NULL,
                          status text  NOT NULL,
                          service_bay_id int  NOT NULL,
                          service_category_id int  NOT NULL,

                          CONSTRAINT check_services_status
                              CHECK (status IN ('active', 'suspended'))
);

