SET search_path TO carfix;

CREATE TABLE opening_hours (
                               opening_hour_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               day_of_week text  NOT NULL,
                               start_time time  NOT NULL,
                               close_time time  NOT NULL,
                               branch_id uuid  NOT NULL,

                               CONSTRAINT check_opening_hours
                                   CHECK (day_of_week
                                       IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')
                                       )
);

