SET search_path TO carfix;

CREATE TABLE opening_hours_exceptions (
                                          exceptions_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          date date  NOT NULL,
                                          start_time time,
                                          close_time time,
                                          is_open boolean  NOT NULL,
                                          reason varchar(300),
                                          branch_id uuid  NOT NULL
);

