SET search_path TO carfix;

CREATE TABLE regions (
                         region_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100)  NOT NULL,
                         countries_iso varchar(2)  NOT NULL
);

