SET search_path TO carfix;

CREATE TABLE employees_availability (
                                        employee_availability_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                        available_time tsrange  NOT NULL,
                                        date date  NOT NULL,
                                        employee_id uuid  NOT NULL,

                                        CONSTRAINT gist_available_time_exclusion_employees_availability
                                            EXCLUDE USING gist (
            date WITH =,
            available_time WITH &&,
            employee_id WITH =
        ),

                                        CONSTRAINT check_available_time_valid_range_employees_availability
                                            CHECK (lower(available_time) < upper(available_time)),
                                        CONSTRAINT check_available_time_not_empty_range_employees_availability
                                            CHECK (NOT isempty(available_time)),
                                        CONSTRAINT check_available_time_has_bounds_employees_availability
                                            CHECK (NOT lower_inf(available_time) AND NOT upper_inf(available_time)),

                                        CONSTRAINT check_available_time_within_one_date_employees_availability
                                            CHECK (
                                                lower(available_time) >= date::timestamp
                                                    AND
                                                upper(available_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

