SET search_path TO carfix;

CREATE TABLE employees_bookings (
                                    employee_booking_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    booked_time tsrange  NOT NULL,
                                    date date  NOT NULL,
                                    employee_id uuid  NOT NULL,
                                    booking_id uuid  NOT NULL,

                                    CONSTRAINT gist_time_exclusion_employees_bookings
                                        EXCLUDE USING gist (
            date WITH =,
            booked_time WITH &&,
            employee_id WITH =
        ),

                                    CONSTRAINT check_available_time_valid_range_employees_bookings
                                        CHECK (lower(booked_time) < upper(booked_time)),
                                    CONSTRAINT check_available_time_not_empty_range_employees_bookings
                                        CHECK (NOT isempty(booked_time)),
                                    CONSTRAINT check_available_time_has_bounds_employees_bookings
                                        CHECK (NOT lower_inf(booked_time) AND NOT upper_inf(booked_time)),

                                    CONSTRAINT check_booked_time_within_one_date_employees_bookings
                                        CHECK (
                                            lower(booked_time) >= date::timestamp
                                                AND
                                            upper(booked_time) < (date::timestamp + INTERVAL '1 day')::timestamp
)
    );

