SET search_path TO carfix;

CREATE TABLE service_equipment_requirements (
                                                service_equipment_requirement_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                name varchar(100)  NOT NULL,
                                                service_id int  NOT NULL
);

ALTER TABLE service_equipment_requirements ADD CONSTRAINT fk_service_equipment_requirements_services FOREIGN KEY (service_id) REFERENCES services (service_id);
