SET search_path TO carfix;

CREATE TABLE cities (
                        city_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100)  NOT NULL,
                        region_id int  NOT NULL
);

