SET search_path TO carfix;

CREATE TABLE streets (
                         street_id bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100)  NOT NULL,
                         city_id int  NOT NULL
);

