SET search_path TO carfix;

CREATE TABLE postal_codes (
                              postal_code_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              code varchar(10) NOT NULL,
                              city_id int  NOT NULL
);

CREATE UNIQUE INDEX ui_postal_codes_city_code
    ON postal_codes (city_id, code);

