SET search_path TO carfix;

CREATE TABLE addresses (
    address_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_name varchar(100) NOT NULL,
    building_number varchar(10)  NOT NULL,
    flat_number varchar(10)  NULL,
    postal_code varchar(10) NOT NULL,
    city_id INT NOT NULL
);

