SET search_path TO carfix;

CREATE TABLE addresses (
                           address_id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           building_number varchar(10)  NOT NULL,
                           flat_number varchar(10)  NULL,
                           street_id bigint  NOT NULL,
                           postal_code_id int  NOT NULL
);

